### ISSUE TITLE
how to use instructions into readme

### ISSUE THREAD

**Issue by vilkoviak** [strideynet/bsky-furry-feed#1]
![image](https://github.com/strideynet/bsky-furry-feed/assets/70372508/1e01e807-2730-4a6f-a179-2fe5b9430cc3)

https://skyfeed.app

![image](https://github.com/strideynet/bsky-furry-feed/assets/70372508/419b1b17-f3ee-4a0a-bb0d-84a1351117d1)

**Comment by strideynet** [comment]
:) I'm actually hoping to add an instructional website to https://furryli.st - I just need to find the energy to write some HTML :3

**Comment by vilkoviak** [comment]
github pages is very convenient

**Comment by strideynet** [comment]
https://furryli.st/
