### ISSUE TITLE
add support for "pinned" users on certain feeds

### ISSUE THREAD

**Issue by itstolf** [strideynet/bsky-furry-feed#131]
for e.g. con feeds, it may be useful to just always put con account skeets onto the feed even if they aren't tagged with the con.

one consideration is that if bff does not know about the con account, it won't ingest any of its posts. should the con account be added directly into the database without requiring them to follow furryli.st? should con skeets be shown on other feeds too?

**Comment by strideynet** [comment]
Closed by #156
