### ISSUE TITLE
RBAC for Moderation API

### ISSUE THREAD

**Issue by strideynet** [strideynet/bsky-furry-feed#77]
We need the ability to have less privileged moderators during their training period. An RBAC model based on casbin or OPA will give us the flexibility to tune this to our needs.

**Comment by hsluoyz** [comment]
Hi @strideynet , I'm from Cabsin team. For your moderator scenario, I think we can use a RBAC model: https://casbin.org/docs/rbac together with the ABAC model: https://casbin.org/docs/abac . Let me know if you have any questions!
